### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by qiaoqiangPro** [zihang-xu/ASC#1]
Hello, Xu:
     Can you provide about target 80 FeTA2021 dataset and source ATLAS dataset in your paper?

**Comment by zihang-xu** [comment]
I have updated the details of the dataset, please check

**Comment by qiaoqiangPro** [comment]
> I have updated the details of the dataset, please check

Oh，谢谢您徐学长，请问可以加您个联系方式请教一个问题吗

**Comment by qiaoqiangPro** [comment]
> > I have updated the details of the dataset, please check
> 
> Oh，谢谢您徐学长，请问可以加您个联系方式请教一个问题吗

我的email是 qiaobetter@163.com

**Comment by qiaoqiangPro** [comment]
In asc.py 
from transform import transform

but in the folder I can not find this transform .py

**Comment by zihang-xu** [comment]
> ###
> [Jan 2, 2024](#issuecomment-1874038248)

You can comment out this line of code and I'll check all the files later.

**Comment by qiaoqiangPro** [comment]
> > [Jan 2, 2024](#issuecomment-1874038248)
> 
> You can comment out this line of code and I'll check all the files later.

Thank you, Xu. Thank you for your help with the datacenter.
`train.list, test.list`is also not clear, may have some difficulties in reproducing.
